name: Component Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag version to release (e.g. 1.2.3)'
        required: true
        type: string

jobs:
  release:
    uses: rdkcentral/entservices-testframework/.github/workflows/component-release.yml@feature/RDKEMW-18857
    with:
      tag: ${{ inputs.tag }}
    secrets: inherit
